enum RibbonEnums {
    // Ordered by introduction. Please add new ribbons at the bottom. Thanks
    // Feel free to rename these to better reflect pokeclicker gameplay or obtain methods
    // Gen 3
    'Champion', // Base champion placeholder
    'Normal_Cool',
    'Normal_Beautiful',
    'Normal_Cute',
    'Normal_Smart',
    'Normal_Tough',
    'Super_Cool',
    'Super_Beautiful',
    'Super_Cute',
    'Super_Smart',
    'Super_Tough',
    'Hyper_Cool',
    'Hyper_Beautiful',
    'Hyper_Cute',
    'Hyper_Smart',
    'Hyper_Tough',
    'Master_Cool',
    'Master_Beautiful',
    'Master_Cute',
    'Master_Smart',
    'Master_Tough',
    'Winning',
    'Victory',
    'Effort',
    'Artist',
    'Country',
    'National',
    'Earth',
    'World',
    'Marine',
    'Land',
    'Sky',
    // Gen 4
    'Sinnoh_Champion',
    'Super_Normal_Cool',
    'Super_Normal_Beautiful',
    'Super_Normal_Cute',
    'Super_Normal_Smart',
    'Super_Normal_Tough',
    'Super_Great_Cool',
    'Super_Great_Beautiful',
    'Super_Great_Cute',
    'Super_Great_Smart',
    'Super_Great_Tough',
    'Super_Ultra_Cool',
    'Super_Ultra_Beautiful',
    'Super_Ultra_Cute',
    'Super_Ultra_Smart',
    'Super_Ultra_Tough',
    'Super_Master_Cool',
    'Super_Master_Beautiful',
    'Super_Master_Cute',
    'Super_Master_Smart',
    'Super_Master_Tough',
    'Ability',
    'Great_Ability',
    'Double_Ability',
    'Multi_Ability',
    'Pair_Ability',
    'World_Ability',
    'Alert',
    'Shock',
    'Downcast',
    'Careless',
    'Relax',
    'Snooze',
    'Smile',
    'Gorgeous',
    'Royal',
    'Gorgeous_Royal',
    'Footprint',
    'Record',
    'Legend',
    'Classic',
    'Premier',
    'History',
    'Red',
    'Green',
    'Blue',
    'Festival',
    'Carnival',
    // Gen 5
    'Event',
    'Birthday',
    'Special',
    'Souvenir',
    'Wishing',
    'Battle_Champion',
    'Regional_Champion',
    'National_Champion',
    'World_Champion',
    // Gen 6
    'Kalos_Champion',
    'Hoenn_Champion',
    'Spectacular_Cool',
    'Spectacular_Beautiful',
    'Spectacular_Cute',
    'Spectacular_Smart',
    'Spectacular_Tough',
    'Spectacular_Star',
    'Contest_Memory',
    'Contest_Memory_Gold',
    'Skillful_Battler',
    'Expert_Battler',
    'Battle_Memory',
    'Battle_Memory_Gold',
    'Best_Friends',
    'Training',
    // Gen 7
    'Alola_Champion',
    'Battle_Royal_Master',
    'Battle_Tree_Great',
    'Battle_Tree_Master',
    // Gen 8
    'Galar_Champion',
    'Brilliant_Shining_Star',
    'Tower_Master',
    'Master_Rank',
    'Pioneer',
    // Gen 9
    'Paldea_Champion',
    'Once-in-a-Lifetime',
    'Partner',
}

export default RibbonEnums;
